<div  data-flux-skeleton-group>
    <div class="[:where(&amp;)]:w-full [:where(&amp;)]:h-5 py-[3px] relative before:absolute before:inset-0 before:-translate-x-full overflow-hidden isolate [:where(&amp;)]:[--flux-shimmer-color:white] dark:[:where(&amp;)]:[--flux-shimmer-color:var(--color-zinc-900)] before:z-10 before:animate-[flux-shimmer_2s_infinite] before:bg-gradient-to-r before:from-transparent before:via-[var(--flux-shimmer-color)]/50 dark:before:via-[var(--flux-shimmer-color)]/50 before:to-transparent mb-2 w-1/4" data-flux-skeleton-line>
    <div class="h-full [:where(&)]:rounded [:where(&)]:bg-zinc-400/20"></div>
</div>    <div class="[:where(&amp;)]:w-full [:where(&amp;)]:h-5 py-[3px] relative before:absolute before:inset-0 before:-translate-x-full overflow-hidden isolate [:where(&amp;)]:[--flux-shimmer-color:white] dark:[:where(&amp;)]:[--flux-shimmer-color:var(--color-zinc-900)] before:z-10 before:animate-[flux-shimmer_2s_infinite] before:bg-gradient-to-r before:from-transparent before:via-[var(--flux-shimmer-color)]/50 dark:before:via-[var(--flux-shimmer-color)]/50 before:to-transparent" data-flux-skeleton-line>
    <div class="h-full [:where(&)]:rounded [:where(&)]:bg-zinc-400/20"></div>
</div>    <div class="[:where(&amp;)]:w-full [:where(&amp;)]:h-5 py-[3px] relative before:absolute before:inset-0 before:-translate-x-full overflow-hidden isolate [:where(&amp;)]:[--flux-shimmer-color:white] dark:[:where(&amp;)]:[--flux-shimmer-color:var(--color-zinc-900)] before:z-10 before:animate-[flux-shimmer_2s_infinite] before:bg-gradient-to-r before:from-transparent before:via-[var(--flux-shimmer-color)]/50 dark:before:via-[var(--flux-shimmer-color)]/50 before:to-transparent" data-flux-skeleton-line>
    <div class="h-full [:where(&)]:rounded [:where(&)]:bg-zinc-400/20"></div>
</div>    <div class="[:where(&amp;)]:w-full [:where(&amp;)]:h-5 py-[3px] relative before:absolute before:inset-0 before:-translate-x-full overflow-hidden isolate [:where(&amp;)]:[--flux-shimmer-color:white] dark:[:where(&amp;)]:[--flux-shimmer-color:var(--color-zinc-900)] before:z-10 before:animate-[flux-shimmer_2s_infinite] before:bg-gradient-to-r before:from-transparent before:via-[var(--flux-shimmer-color)]/50 dark:before:via-[var(--flux-shimmer-color)]/50 before:to-transparent w-3/4" data-flux-skeleton-line>
    <div class="h-full [:where(&)]:rounded [:where(&)]:bg-zinc-400/20"></div>
</div>
</div><?php /**PATH /var/www/html/totthobox/storage/framework/views/0b44b39ff7a7a7010b0365f0f5be90c0.blade.php ENDPATH**/ ?>