<?php

/**
 * ╔══════════════════════════════════════════════════════════════════════════╗
 * ║   config/content_agent.php — SINGLE SOURCE OF TRUTH                      ║
 * ║   AutoImproveContent command এবং AutonomousContentAgent দুটোই এখান       ║
 * ║   থেকে model registry পড়বে। আগের মতো দুই জায়গায় আলাদা list রাখা লাগবে না। ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 *
 * প্রতিটা model entry এর ফিল্ডসমূহ:
 *
 *  class            → Model এর fully-qualified class name
 *  display_name     → AI/UI এর জন্য human-readable নাম
 *  topic            → generation prompt এ ব্যবহৃত হবে
 *  min_rows         → এর কম row থাকলে auto-generate ট্রিগার হবে
 *  quality_fields   → এই fields দিয়ে quality score করা হবে (runtime এ শুধু
 *                      যেগুলো actually column হিসেবে exist করে সেগুলোই ব্যবহার হবে)
 *  seed_topics      → (optional) coverage-gap detection এর জন্য নির্দিষ্ট topic list।
 *                      খালি রাখলে agent AI কে দিয়ে generic instruction বানাবে।
 *  grounding        → true হলে generation এর আগে Wikipedia থেকে fact snippet
 *                      টেনে এনে prompt এ inject করবে (hallucination কমাতে)
 *  max_generate     → এক রানে সর্বোচ্চ কতটা নতুন record বানাবে
 */

return [

    // কম score হলে remake candidate হিসেবে ধরা হবে
    'quality_threshold' => 65,

    // true হলে LLM-judge দিয়ে score হবে, false হলে পুরনো regex-heuristic fallback
    'judge_enabled' => env('CONTENT_AGENT_JUDGE_ENABLED', true),

    // এক ব্যাচে সর্বোচ্চ কতটা রেকর্ড audit করবে
    'score_batch_size' => 20,

    // প্রতি মডেল প্রসেসের মাঝে কত সেকেন্ড gap (rate-limit বাঁচাতে, sync mode এ)
    'inter_model_delay' => 2,

    'models' => [

        // ── Location & Administrative ──────────────────────────────────────
        'Division' => [
            'class' => \App\Models\Division::class,
            'display_name' => 'Bangladesh Divisions',
            'topic' => 'বাংলাদেশের বিভাগসমূহ',
            'min_rows' => 8,
            'quality_fields' => ['name', 'description'],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 8,
        ],
        'District' => [
            'class' => \App\Models\District::class,
            'display_name' => 'Bangladesh Districts',
            'topic' => 'বাংলাদেশের জেলাসমূহ',
            'min_rows' => 64,
            'quality_fields' => ['name', 'description'],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 15,
        ],
        'Thana' => [
            'class' => \App\Models\Thana::class,
            'display_name' => 'Bangladesh Thanas/Upazilas',
            'topic' => 'বাংলাদেশের থানা/উপজেলা',
            'min_rows' => 100,
            'quality_fields' => ['name'],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 15,
        ],

        // ── Core Content Models ──────────────────────────────────────────────
        'TourismBd' => [
            'class' => \App\Models\TourismBd::class,
            'display_name' => 'Bangladesh Tourism Spots',
            'topic' => 'বাংলাদেশের বিখ্যাত পর্যটন স্থান, ইতিহাস, কীভাবে যাবেন, কী দেখবেন',
            'min_rows' => 60,
            'quality_fields' => ['name', 'description', 'title'],
            // ★ Coverage-gap seed: ৬৪ জেলার নাম — agent প্রতিটা জেলার spot cover হয়েছে কিনা চেক করবে
            'seed_topics' => [
                'ঢাকা',
                'গাজীপুর',
                'নারায়ণগঞ্জ',
                'টাঙ্গাইল',
                'মুন্শিগঞ্জ',
                'মানিকগঞ্জ',
                'নরসিংদী',
                'কিশোরগঞ্জ',
                'ফরিদপুর',
                'গোপালগঞ্জ',
                'মাদারীপুর',
                'রাজবাড়ী',
                'শরীয়তপুর',
                'চট্টগ্রাম',
                'কক্সবাজার',
                'বান্দরবান',
                'রাঙামাটি',
                'খাগড়াছড়ি',
                'কুমিল্লা',
                'ফেনী',
                'নোয়াখালী',
                'লক্ষ্মীপুর',
                'চাঁদপুর',
                'ব্রাহ্মণবাড়িয়া',
                'সিলেট',
                'মৌলভীবাজার',
                'হবিগঞ্জ',
                'সুনামগঞ্জ',
                'রাজশাহী',
                'নাটোর',
                'নওগাঁ',
                'চাঁপাইনবাবগঞ্জ',
                'পাবনা',
                'সিরাজগঞ্জ',
                'বগুড়া',
                'জয়পুরহাট',
                'রংপুর',
                'দিনাজপুর',
                'ঠাকুরগাঁও',
                'পঞ্চগড়',
                'নীলফামারী',
                'লালমনিরহাট',
                'কুড়িগ্রাম',
                'গাইবান্ধা',
                'খুলনা',
                'যশোর',
                'সাতক্ষীরা',
                'বাগেরহাট',
                'নড়াইল',
                'মাগুরা',
                'ঝিনাইদহ',
                'কুষ্টিয়া',
                'চুয়াডাঙ্গা',
                'মেহেরপুর',
                'বরিশাল',
                'পটুয়াখালী',
                'ভোলা',
                'পিরোজপুর',
                'বরগুনা',
                'ঝালকাঠি',
                'ময়মনসিংহ',
                'জামালপুর',
                'শেরপুর',
                'নেত্রকোণা',
            ],
            'grounding' => true,
            'max_generate' => 15,
        ],
        'HistoryBd' => [
            'class' => \App\Models\HistoryBd::class,
            'display_name' => 'Bangladesh History',
            'topic' => 'বাংলাদেশের ঐতিহাসিক ঘটনা, মুক্তিযুদ্ধ, সংস্কৃতি ও ঐতিহ্য',
            'min_rows' => 30,
            'quality_fields' => ['name', 'description'],
            'seed_topics' => [
                'ভাষা আন্দোলন ১৯৫২',
                'মুক্তিযুদ্ধ ১৯৭১',
                'ছয় দফা আন্দোলন',
                'গণঅভ্যুত্থান ১৯৬৯',
                'অসহযোগ আন্দোলন',
                '৭ই মার্চের ভাষণ',
                'মুজিবনগর সরকার',
                'বঙ্গভঙ্গ ১৯০৫',
                'পলাশীর যুদ্ধ',
                'নীল বিদ্রোহ',
                'ফকির-সন্ন্যাসী বিদ্রোহ',
                'তিতুমীরের বিদ্রোহ',
                'দেশভাগ ১৯৪৭',
                'গণহত্যা ১৯৭১',
                'জাতীয় চার নেতা হত্যা',
                'বাংলা নববর্ষের ইতিহাস',
            ],
            'grounding' => true,
            'max_generate' => 12,
        ],
        'IntroBd' => [
            'class' => \App\Models\IntroBd::class,
            'display_name' => 'Introduction to Bangladesh',
            'topic' => 'বাংলাদেশ পরিচিতি — ভূগোল, জনসংখ্যা, অর্থনীতি, সংস্কৃতি',
            'min_rows' => 10,
            'quality_fields' => ['name', 'description'],
            'seed_topics' => [],
            'grounding' => true,
            'max_generate' => 10,
        ],
        'EstablishmentBd' => [
            'class' => \App\Models\EstablishmentBd::class,
            'display_name' => 'Bangladesh Establishments',
            'topic' => 'বাংলাদেশের গুরুত্বপূর্ণ প্রতিষ্ঠান — সরকারি ও বেসরকারি',
            'min_rows' => 15,
            'quality_fields' => ['name', 'description'],
            'seed_topics' => [],
            'grounding' => true,
            'max_generate' => 10,
        ],
        'Hospital' => [
            'class' => \App\Models\Hospital::class,
            'display_name' => 'Bangladesh Hospitals',
            'topic' => 'বাংলাদেশের হাসপাতাল ও স্বাস্থ্যসেবা প্রতিষ্ঠান',
            'min_rows' => 15,
            'quality_fields' => ['name', 'description'],
            'seed_topics' => [],
            'grounding' => true,
            'max_generate' => 10,
        ],
        // ── Religious & Educational ──────────────────────────────────────────
        'BasicIslam' => [
            'class' => \App\Models\BasicIslam::class,
            'display_name' => 'Basic Islam Topics',
            'topic' => 'ইসলামের মৌলিক বিষয়, নামাজ, রোজা, হজ, যাকাত, আকিদা',
            'min_rows' => 30,
            'quality_fields' => ['name', 'description'],
            'seed_topics' => [
                'নামাজের নিয়ম',
                'অজুর নিয়ম',
                'রোজার নিয়ম',
                'যাকাতের হিসাব',
                'হজের নিয়ম',
                'তায়াম্মুম',
                'জানাজার নামাজ',
                'তারাবির নামাজ',
                'ঈদের নামাজ',
                'কুরবানির নিয়ম',
                'ইসলামে বিবাহ',
                'ইসলামে উত্তরাধিকার',
                'তওবার গুরুত্ব',
                'সালাতুল ইস্তেখারা',
                'ইসলামে সততার গুরুত্ব',
                'পাঁচ কালিমা',
                'ইসলামের রুকন',
                'ইমানের রুকন',
            ],
            'grounding' => false, // ধর্মীয় বিষয়ে Wikipedia নির্ভরযোগ্য primary source না — আলাদা বিশ্বস্ত reference লাগবে
            'max_generate' => 12,
        ],
        'Sura' => [
            'class' => \App\Models\Sura::class,
            'display_name' => 'Quran Suras',
            'topic' => 'কুরআনের সূরাসমূহ',
            'min_rows' => 114,
            'quality_fields' => ['name'],
            'seed_topics' => [],
            'grounding' => false, // ★ সতর্কতা: কুরআনের টেক্সট AI দিয়ে generate করা উচিত না, verified source থেকে import করুন
            'max_generate' => 5,
        ],
        'Dowa' => [
            'class' => \App\Models\Dowa::class,
            'display_name' => 'Islamic Duas',
            'topic' => 'ইসলামিক দোয়া সমূহ',
            'min_rows' => 30,
            'quality_fields' => ['name', 'description'],
            'seed_topics' => [],
            'grounding' => false, // ★ একই সতর্কতা — দোয়ার আরবি টেক্সট verified source থেকে নিন
            'max_generate' => 10,
        ],
        'Quran' => [
            'class' => \App\Models\Quran::class,
            'display_name' => 'Quran Verses',
            'topic' => 'কুরআনের আয়াতসমূহ',
            'min_rows' => 0, // ★ AI generation বন্ধ রাখা হয়েছে — নিচে auto_generate_disabled দ্রষ্টব্য
            'quality_fields' => [],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 0,
            'auto_generate_disabled' => true, // agent এই model স্কিপ করবে generation এ
        ],
        'Subject' => [
            'class' => \App\Models\Subject::class,
            'display_name' => 'Academic Subjects',
            'topic' => 'শিক্ষা বিষয়ক সাবজেক্ট তালিকা',
            'min_rows' => 15,
            'quality_fields' => ['name'],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 10,
        ],
        'ClassLevel' => [
            'class' => \App\Models\ClassLevel::class,
            'display_name' => 'Class Levels',
            'topic' => 'শ্রেণী/ক্লাস লেভেল তালিকা',
            'min_rows' => 12,
            'quality_fields' => ['name'],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 10,
        ],
        'ExcelTutorial' => [
            'class' => \App\Models\ExcelTutorial::class,
            'display_name' => 'Excel Tutorials in Bengali',
            'topic' => 'Microsoft Excel টিউটোরিয়াল — সূত্র, ফাংশন, চার্ট, ডেটা বিশ্লেষণ বাংলায়',
            'min_rows' => 25,
            'quality_fields' => ['name', 'description'],
            'seed_topics' => [
                'VLOOKUP ফাংশন',
                'HLOOKUP ফাংশন',
                'IF ফাংশন',
                'SUMIF ফাংশন',
                'COUNTIF ফাংশন',
                'Pivot Table',
                'VBA ম্যাক্রো বেসিক',
                'Conditional Formatting',
                'Data Validation',
                'INDEX MATCH',
                'চার্ট তৈরি',
                'ফ্রিজ প্যান',
                'শীট প্রোটেকশন',
                'XLOOKUP ফাংশন',
            ],
            'grounding' => false,
            'max_generate' => 12,
        ],

        // ── Health & Food ─────────────────────────────────────────────────────
        'BasicHealth' => [
            'class' => \App\Models\BasicHealth::class,
            'display_name' => 'Basic Health Information',
            'topic' => 'স্বাস্থ্য বিষয়ক তথ্য, রোগ, চিকিৎসা, স্বাস্থ্যকর জীবনযাপন',
            'min_rows' => 25,
            'quality_fields' => ['name', 'description'],
            'seed_topics' => [
                'ডায়াবেটিস',
                'উচ্চ রক্তচাপ',
                'জ্বর',
                'সর্দি-কাশি',
                'ডেঙ্গু জ্বর',
                'টাইফয়েড',
                'হৃদরোগ',
                'কিডনি রোগ',
                'গ্যাস্ট্রিক',
                'আর্থ্রাইটিস',
                'অ্যাজমা',
                'মাইগ্রেন',
            ],
            'grounding' => true,
            'max_generate' => 12,
        ],
        'Food' => [
            'class' => \App\Models\Food::class,
            'display_name' => 'Bangladeshi Food',
            'topic' => 'বাংলাদেশের ঐতিহ্যবাহী খাবার, রেসিপি, পুষ্টিগুণ',
            'min_rows' => 30,
            'quality_fields' => ['name', 'description'],
            'seed_topics' => [
                'ইলিশ মাছ ভাজা',
                'খিচুড়ি',
                'ভর্তা',
                'পান্তা ভাত',
                'বিরিয়ানি',
                'হালিম',
                'পিঠা',
                'মিষ্টি দই',
                'রসগোল্লা',
                'সন্দেশ',
                'ফুচকা',
                'চটপটি',
                'ঝালমুড়ি',
            ],
            'grounding' => true,
            'max_generate' => 12,
        ],
        'Nutrient' => [
            'class' => \App\Models\Nutrient::class,
            'display_name' => 'Nutrients',
            'topic' => 'পুষ্টি উপাদান তালিকা',
            'min_rows' => 20,
            'quality_fields' => ['name'],
            'seed_topics' => [],
            'grounding' => true,
            'max_generate' => 10,
        ],
        'FoodNutrient' => [
            'class' => \App\Models\FoodNutrient::class,
            'display_name' => 'Food-Nutrient Mapping',
            'topic' => 'খাবার ও পুষ্টি উপাদানের সম্পর্ক',
            'min_rows' => 0,
            'quality_fields' => [],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 0,
            'auto_generate_disabled' => true, // pivot-heavy, manual/relation-driven রাখাই ভালো
        ],

        // ── People & Contacts ─────────────────────────────────────────────────
        'Person' => [
            'class' => \App\Models\Person::class,
            'display_name' => 'Notable Persons of Bangladesh',
            'topic' => 'বাংলাদেশের বিখ্যাত ব্যক্তিত্ব — কবি, রাজনীতিবিদ, বিজ্ঞানী, শিল্পী',
            'min_rows' => 25,
            'quality_fields' => ['name', 'bio'],
            'seed_topics' => [],
            'grounding' => true,
            'max_generate' => 10,
        ],
        'Position' => [
            'class' => \App\Models\Position::class,
            'display_name' => 'Government Positions',
            'topic' => 'সরকারি পদবি তালিকা',
            'min_rows' => 15,
            'quality_fields' => ['name'],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 10,
        ],
        'ContactNumber' => [
            'class' => \App\Models\ContactNumber::class,
            'display_name' => 'Emergency Contact Numbers',
            'topic' => 'জরুরি যোগাযোগ নম্বর',
            'min_rows' => 0,
            'quality_fields' => [],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 0,
            'auto_generate_disabled' => true, // ★ ফোন নম্বর কখনোই AI দিয়ে বানাবেন না — ভুল নম্বর বিপজ্জনক
        ],
        'PeopleCategory' => [
            'class' => \App\Models\PeopleCategory::class,
            'display_name' => 'People Categories',
            'topic' => 'ব্যক্তিত্বদের ক্যাটাগরি',
            'min_rows' => 10,
            'quality_fields' => ['name'],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 10,
        ],

        // ── Business & News ───────────────────────────────────────────────────
        'BuySellItem' => [
            'class' => \App\Models\BuySellItem::class,
            'display_name' => 'Buy/Sell Items',
            'topic' => 'কেনাবেচার আইটেম ক্যাটাগরি',
            'min_rows' => 0,
            'quality_fields' => [],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 0,
            'auto_generate_disabled' => true, // ★ user-generated marketplace ডেটা — fake AI listing বানানো উচিত না
        ],
        'BuySellPost' => [
            'class' => \App\Models\BuySellPost::class,
            'display_name' => 'Buy/Sell Posts',
            'topic' => 'কেনাবেচার পোস্ট',
            'min_rows' => 0,
            'quality_fields' => [],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 0,
            'auto_generate_disabled' => true, // ★ একই কারণ — user marketplace content, fake করবেন না
        ],
        'NewsHeading' => [
            'class' => \App\Models\NewsHeading::class,
            'display_name' => 'News Headlines',
            'topic' => 'সংবাদ শিরোনাম',
            'min_rows' => 0,
            'quality_fields' => [],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 0,
            'auto_generate_disabled' => true, // ★ ইতিমধ্যে NewsScraperService দিয়ে real news scrape হচ্ছে — AI দিয়ে fake news বানাবেন না
        ],

        // ── Others ────────────────────────────────────────────────────────────
        'Holiday' => [
            'class' => \App\Models\Holiday::class,
            'display_name' => 'Bangladesh Holidays',
            'topic' => 'বাংলাদেশের সরকারি ছুটির দিন',
            'min_rows' => 0,
            'quality_fields' => [],
            'seed_topics' => [],
            'grounding' => true,
            'max_generate' => 0,
            'auto_generate_disabled' => true, // ★ তারিখ-নির্ভর সরকারি তথ্য — ভুল হলে মানুষ বিভ্রান্ত হবে, manual verify করুন
        ],
        'Sign' => [
            'class' => \App\Models\Sign::class,
            'display_name' => 'Traffic/Road Signs',
            'topic' => 'ট্রাফিক ও রোড সাইন',
            'min_rows' => 15,
            'quality_fields' => ['name', 'description'],
            'seed_topics' => [],
            'grounding' => true,
            'max_generate' => 10,
        ],
        'Question' => [
            'class' => \App\Models\Question::class,
            'display_name' => 'Quiz Questions',
            'topic' => 'সাধারণ জ্ঞান প্রশ্ন',
            'min_rows' => 30,
            'quality_fields' => ['name'],
            'seed_topics' => [],
            'grounding' => true,
            'max_generate' => 15,
        ],
        'Test' => [
            'class' => \App\Models\Test::class,
            'display_name' => 'Tests',
            'topic' => 'টেস্ট মডেল',
            'min_rows' => 0,
            'quality_fields' => [],
            'seed_topics' => [],
            'grounding' => false,
            'max_generate' => 0,
            'auto_generate_disabled' => true,
        ],
    ],
];